### ISSUE TITLE
Wie wird das Einloggen via key aktiviert?

### ISSUE THREAD

**Issue by rustykowski** [thescrat/contao-loginlink#1]
Contao 4.9:
In der Tabelle tl_page sehe ich zwar die beiden Felder loginlink_length und loginlink, ich kann die Einstellung jedoch im Startpunkt nicht entdecken.
Momentan funktioniert das Einloggen via key auch noch nicht, vermutlich, weil die generelle Aktivierung im Startpunkt fehlt. Was kann ich tun?

**Comment by thescrat** [comment]
In der Readme steht eigentlich ganz klar wie es geht. Ob es allerdings unter 4.9 geht kann ich nicht sagen, wird ja ständig was geändert. Habe 4.9 nicht im Einsatz und auch bisher nicht getestet

**Comment by rustykowski** [comment]
Im der Readme steht:
> Im Root-Seitenelement kann der Login für die Seitenstruktur erlaubt werden.

Dies ist aber leider nicht möglich. Es gibt keine derartige Einstellung.

**Comment by rustykowski** [comment]
In C 4.8 erscheinen im Startpunkt die Login-Link Einstellungen zwischen den Paletten Zugriffsschutz und Layouteinstellungen. In C 4.9 fehlt die Palette.

**Comment by rustykowski** [comment]
Das Einloggen via key funktioniert, wenn man die Felder in der DB-Tabelle tl_page händisch setzt. Das einzige Problem betrifft also die fehlende Palette im Contao-Backend.

**Comment by thescrat** [comment]
Ah ok, danke für den Hinweis. Damit dürfte das Problem ja zum Glück schnell behoben sein. Werde asap ne korrigierte Version rausbringen. Händisch setzen hast du ja schon gemacht, damit ist es ja erstmal funktionell :-)

**Comment by thkuegler** [comment]
Möglicher Fix im dca tl_page:
$palette = \Contao\CoreBundle\DataContainer\PaletteManipulator::create()
    ->addLegend('loginlink_legend', 'protected_legend', \Contao\CoreBundle\DataContainer\PaletteManipulator::POSITION_BEFORE, true)
    ->addField(['loginlink'], 'loginlink_legend', \Contao\CoreBundle\DataContainer\PaletteManipulator::POSITION_APPEND)
    ->applyToPalette('root', 'tl_page')
;

if (isset($GLOBALS['TL_DCA']['tl_page']['palettes']['rootfallback'])) {
    $palette->applyToPalette('rootfallback', 'tl_page');
}
