### ISSUE TITLE
loginLink Schlüssellänge im Registrierungsmodul lediglich 26 digits

### ISSUE THREAD

**Issue by ThomasKettner** [thescrat/contao-loginlink#10]
Die Länge des Login Schlüssels habe ich in den Einstellungen auf 50 gesetzt.
Beim Speichern oder Generieren über das Backend wird dies auch ordnungsgemäß berücksichtigt.
Bei einer Neuregistrierung werden allerdings lediglich 26 digits verwendet.

Wäre es möglich, den Schlüssel gleich bei der Registrierung zu erzeugen?
Ich nutze das Notification Center und aktuell ist der Schlüssel erst bei der 2. Mail (Aktivierungsmail) als Token verfügbar.
Ich würde ihn aber gerne bereits in der 1. Mail mit dem Bestätigungslink anhängen.
Dann könnte ich das Mitglied sofort mit der Bestätigung in den internen Bereich leiten.

**Comment by ThomasKettner** [comment]
Hi, hast du evtl. eine Rückmeldung zu diesem Bug?

**Comment by rustykowski** [comment]
Hast du in den Systemeinstellungen > LoginLink-Einstellungen "Automatisch für neue Mitglieder" aktiviert?
Die gewünschte Standardlänge scheint nicht berücksichtigt zu werden, das beobachte ich auch so.

**Comment by ThomasKettner** [comment]
Ja ich habe alles aktiviert und nutze es bereits produktiv für neue Mitglieder. 
Der Prozess funktioniert einwandfrei, bis auf die Länge bei der Erstregistrierung.
Sobald ich im Backend das Mitglied bearbeite und einen neuen Token anfordere, ist dieser auch 50 Zeichen lang.

**Comment by rustykowski** [comment]
@ThomasKettner hast du zufällig auch eine Idee zu #11 ?

**Comment by ThomasKettner** [comment]
Leider nein, wir nutzen brevo als Newslettersystem. Hiermit funktioniert es mit brevo-sync einwandfrei.

**Comment by thescrat** [comment]
Ich hab euch gerade ne neue Version bereitgestellt (ist auch schon im Manager verfügbar). Damit müsste der Fehler mit der falschen Schlüssellänge behoben sein.
