### ISSUE TITLE
Token ##loginLink## wird im Newsletter nicht ersetzt

### ISSUE THREAD

**Issue by rustykowski** [thescrat/contao-loginlink#11]
Contao: 4.13.34 | PHP 8.1 | contao-loginlink 1.0.7

Bis vor kurzem konnte ich im Newsletter das Token ##loginLink## verwenden, um Mitgliedern ein automatischen Einloggen per Link zu ermöglichen. Dies wird aber inzwischen nicht mehr ersetzt.
Es gibt keine Fehlermeldungen dazu.

Woran könnte das liegen?

**Comment by thescrat** [comment]
Also ich kanns dir ehrlich gesagt selbst nicht sagen, warum das bis vor kurzem funktioniert hat und jetzt nicht mehr. 

Du könntest es jedoch über diesen Token probieren ##member_loginLink##
Das ist zumindest schon mal der hinterlegte Key. Baust dir halt den Link davor domain.tld/?key=##member_loginLink##
Sowas in der Art. Sollte eigentlich funktionieren

**Comment by rustykowski** [comment]
##member_loginLink## funktioniert in Benachrichtigungen im notification-center.
Im Newsletter leider nicht.

**Comment by thescrat** [comment]
Aber unterstützt der Newsletter denn ## InsertTags?
Wenn ich in der Doku nachschaue sind ja die regulären InsertTags {{user::firstname}}
Probier doch mal im Newsletter {{user::loginLink}}
Also ich kenne die ##member_*## Tags nur vom Notification Center

**Comment by rustykowski** [comment]
Ich bin ein Hornochse.
Natürlich kann man das nicht testen, wenn man die Funktion "Testsendung" nutzt, sondern nur, wenn man den Newsletter regulär an die Empfänger schickt. Und da ist alles in Ordnung.

Im Newsletter benötigt man tatsächlich ##loginLink##, das InsertTag funktioniert nicht, und member_ wird an der Stelle auch nicht benötigt.

Sorry für die Umstände!
