### ISSUE TITLE
Contao 4.13.37 Kompatibilität, Invalid Request Token

### ISSUE THREAD

**Issue by ThomasKettner** [thescrat/contao-loginlink#12]
Nach einem Update auf C4.13.37 erhalten wir bei Registrierung über Registrierungsmodul:
Ungültiges Anfrage-Token
Was ist das Problem?
Das Request-Token konnte nicht validiert werden.

Verlangt die Erweiterung nach einem Request Token bei Registrierung?

https://github.com/contao/contao/blob/e077807b33d7d5d9ebe1294f438ba2972140adb7/core-bundle/src/EventListener/RequestTokenListener.php#L55-L102

**Comment by thescrat** [comment]
Hallo Thomas,
ich habe es gerade in einer frischen Contao 4.13.37 probiert und kann diesen Fehler leider nicht reproduzieren.
Kannst du mir bitte genauer beschreiben nach welchem "Klick" dieser Anfrage-Token Fehler auftritt?

Registrierung + Aktivierungsmail gehe ich mal von aus. Über NotificationCenter oder Contao?
Welche PHP Version hast du im Einsatz? Kannst du den Fehler reproduzieren?

Ich bin nämlich etwas verwundert, denn die Erweiterung hat mit dem Request-Token überhaupt nichts zu tun. Es hängt sich zwar an jeden Seitenaufruf, prüft ob es einen GET Parameter namens "key" gibt.

**Comment by ThomasKettner** [comment]
Vielen Dank,

ich habe nun auch ein paar separate Tests durchgeführt und kann ihn in anderen Installationen nicht reproduzieren. Ich gehe also nicht davon aus, dass es an dieser Erweiterung liegt. Ich war mir nur nicht sicher, ob hier der Request Token eine Rolle spielt. Ich denke wir können das Ticket schließen.
