### ISSUE TITLE
Konflikt psr/log ^1.0 / MetaModels 2.3 braucht 2.0

### ISSUE THREAD

**Issue by tognit** [thescrat/contao-loginlink#13]
Guten Abend

Nach einem Update von MetaModels 2.3 kann ich deine Erweiterung nicht mehr verwenden, bzw. installieren.

> Resolving dependencies using Composer Cloud v3.7.1
  Problem 1
    - thescrat/contao-loginlink[1.0, ..., 1.0.4.1] require php ^7.1 -> your php version (8.1.28.0) does not satisfy that requirement.
    - thescrat/contao-loginlink[1.0.5, ..., 1.0.9] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires thescrat/contao-loginlink ^1.0 -> satisfiable by thescrat/contao-loginlink[1.0, ..., 1.0.9].

**Comment by thescrat** [comment]
Guten Abend, 
habe die Abhängigkeit zum psr/log mal erweitert, dass Version 1,2 und 3 funktionieren müssten. 
Was mich aber verwundert ist die Meldung bzgl. der PHP Version. Hast du Contao 4.9 im Einsatz? Die Änderung sollte eigentlich nur ab Contao 4.13 funktionieren.

**Comment by tognit** [comment]
Die verstehe ich auch nicht ganz, es ist Contao 4.13 und PHP 8.1.xxx

**Comment by tognit** [comment]
Besten Dank! Funktioniert!!!
