### ISSUE TITLE
Error after cache warmup: [] operator not supported for strings

### ISSUE THREAD

**Issue by rustykowski** [thescrat/contao-loginlink#14]
Siehe https://github.com/codefog/contao-events_subscriptions/issues/107

Ich bin nicht sicher, ob der Fehler evtl. mit contao-loginlink zusammenhängen könnte. Er trat jedenfalls nach einer Paketaktualisierung auf, bei der von 1.0.9 auf 1.0.11 gewechselt wurde. Da es um die tl_member Tabelle geht, kam mir der Verdacht.

**Comment by thescrat** [comment]
Da contao-loginlink diesen selector nicht nutzt, kann dieser Fehler also davon nicht kommen. Das kannst du auch recht einfach testen, deinstalliere einfach contao-loginlink kurzfristig (brauchst ja die Tabellen nicht löschen lassen) und mach einen erneuten warmup, der Fehler wieder weiterhin bestehen.

Der Fehler liegt hier: 
https://github.com/codefog/contao-events_subscriptions/blob/master/dca/tl_member.php#L26

Dort müsstest du ein Ticket eröffnen und darum bitten, dass der selector-Index als String hinzugefügt wird
Also so (gibt sicher auch noch andere, schönere Methoden)
$GLOBALS['TL_DCA']['tl_member']['palettes']['__selector__']['subscription_enableLimit'] = 'subscription_enableLimit';

**Comment by rustykowski** [comment]
Danke für deine Einschätzung und deinen Kommentar im codefog-Repo!

**Comment by rustykowski** [comment]
Ist es richtig, dass in 1.0.12 das Feld tl_page.loginlink_length nicht mehr benötigt wird?

<img width="294" alt="image" src="https://github.com/user-attachments/assets/babc4a46-9461-45f5-bc76-1a7047af3e5e">

**Comment by thescrat** [comment]
Ja, das ist korrekt. Es gibt nur noch in den Einstellungen die Anzahl der Zeichen. Ansonsten kannst du den Key und Länge manuell beim Mitglied ändern. Gibt auch kein Feld in der Root-Page wo du das einstellen könntest.

**Comment by rustykowski** [comment]
Danke für die schnelle Hilfe!
