### ISSUE TITLE
Freigeben für 4.13

### ISSUE THREAD

**Issue by akroii** [thescrat/contao-loginlink#5]
Hallo,
ich habe bei einer Beispielinstallation mal ein Upgrade auf 4.13 als Trockenlauf inkl aller Pakete gemacht. Zuvor habe ich ein `composer update` gemacht.
```
{
    "type": "project",
    "require": {
        "alnv/catalog-manager": "^1.31",
        "alnv/catalog-manager-export": "^1.2",
        "alnv/catalog-manager-form-options": "^1.0",
        "alnv/catalog-manager-importer": "^1.3",
        "alnv/catalog-manager-wishlist": "^2.2",
        "bugbuster/contao-be_user_online-bundle": "^2.0",
        "christianbarkowsky/rel-canonical": "^3.3",
        "cliffparnitzky/direct-content-elements": "^1.3",
        "codefog/contao-news_categories": "^3.4",
        "contao-bootstrap/core": "^2.0",
        "contao-bootstrap/form": "^2.1",
        "contao-bootstrap/grid": "^2.3",
        "contao-bootstrap/layout": "^2.0",
        "contao/calendar-bundle": "4.9.*",
        "contao/conflicts": "*@dev",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "4.9.*",
        "craffft/css-style-selector-bundle": "^1.6",
        "derhaeuptling/contao-mega-menu": "^1.0",
        "erdmannfreunde/calendar_feature": "^1.0",
        "erdmannfreunde/euf_hero": "^2.0",
        "erdmannfreunde/theme-toolbox": "^1.0",
        "exotelis/contao-card": "^1.0",
        "fritzmg/contao-file-access": "^2.2",
        "fritzmg/contao-inherit-article": "^3.0",
        "fritzmg/contao-news-related": "^1.3",
        "fritzmg/contao-simple-news-urls": "^3.0",
        "fritzmg/contao-swiper": "^4.0",
        "heimrichhannot/contao-loginredirects-bundle": "^1.0",
        "hh-com/contao-filereplace": "^1.2",
        "hofff/contao-calendarfield": "^4.0",
        "hofff/contao-layoutusage": "^2.1",
        "inspiredminds/contao-eventlist-extended": "^1.2",
        "inspiredminds/contao-wowjs": "^1.1",
        "madeyourday/contao-rocksolid-custom-elements": "^2.3",
        "marebe1602/mae_event_categories": "^1.5",
        "markenzoo/contao-file-helper-bundle": "^2.0",
        "menatwork/synccto": "^4.0",
        "numero2/contao-opengraph3": "^4.2",
        "numero2/contao-proper-filenames": "^2.1",
        "oveleon/contao-cookiebar": "^1.9",
        "pdir/contao-sticky-footer": "^1.0",
        "richardhj/contao-ajax_reload_element": "^2.1",
        "slashworks/contao-simple-svg-icons-bundle": "^1.4",
        "smohring/cearch-pro-bundle": "^1.1",
        "stefansl/contao-divider-bundle": "^1.1",
        "tastaturberuf/contao-doccheck-login-bundle": "^1.0",
        "terminal42/contao-mp_forms": "^4.3",
        "terminal42/contao-url-rewrite": "^1.5",
        "terminal42/notification_center": "^1.6",
        "thescrat/contao-loginlink": "^1.0",
        "trilobit-gmbh/contao-ajaxpagination-bundle": "^1.2",
        "trilobit-gmbh/contao-history-bundle": "^1.0",
        "trilobit-gmbh/contao-tiles-bundle": "^1.0"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
    }
}

```

Ich erhalte folgenden Fehler:
```
> Resolving dependencies using Composer Cloud v3.4.2
!!! Current server is sponsored by: Contao Association !!!
[7.9MiB/0.21s] Loading composer repositories with package information
[76.5MiB/8.02s] Updating dependencies
[147.6MiB/8.58s] Your requirements could not be resolved to an installable set of packages.
[147.6MiB/8.58s] 
  Problem 1
    - Root composer.json requires thescrat/contao-loginlink ^1.0 -> satisfiable by thescrat/contao-loginlink[1.0, ..., 1.0.4].
    - contao/manager-bundle[4.13.0, ..., 4.13.2] require symfony/http-foundation ^5.4 -> satisfiable by symfony/http-foundation[v5.4.0, ..., v5.4.6].
    - Conclusion: don't install symfony/http-foundation v5.4.6 (conflict analysis result)
    - Root composer.json requires contao/manager-bundle 4.13.* -> satisfiable by contao/manager-bundle[4.13.0, 4.13.1, 4.13.2].
Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
[147.6MiB/8.58s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[42.8MiB/8.65s] Memory usage: 42.78MB (peak: 193.96MB), time: 8.66s.
[42.8MiB/8.65s] Finished Composer Cloud resolving.
# Cloud Job ID nyUOuGoKv12seMPlFNcclAnH3KmOk91U6YdF6O82SWtuIpVF1faJP6SHDhS8h28xDfp1BJjOC9Yi4ErW1d7PxUT5pTXmNIaeRJ5Crf5gxCoPvSeY106 failed
```

Kannst du deine Extension auf 4.13 heben? 😊

**Comment by thescrat** [comment]
Hi, ja, weiß ich, hab das selbe Problem. 

Anhebung auf 4.13 wird es so schnell nicht geben, da ich derzeit keine Ahnung habe was ich technisch anpassen muss, damit es wieder läuft....

**Comment by akroii** [comment]
Falls der Aufwand größer sein sollte, kannst du uns auch eine Rechnung schreiben.

**Comment by akroii** [comment]
... wenn die fachliche Hürde zu groß ist, könnte ich auch jemand fragen der die Erweiterung auf 4.13 hebt?

**Comment by agonyz** [comment]
@thescrat @akroii Guten Tag, ich habe gerade leider nicht genug Zeit mich selbst darum zu kümmern, aber der Fehler liegt, wie bereits vermutet, in den Abhängigkeiten, welche in der composer.json definiert wurden.

Dort steht:
```
 "require": {
        "php": "^7.1",
        "contao/core-bundle": "^4.5",
        "doctrine/dbal": "^2.7",
        "psr/log": "^1.0",
        "symfony/config": "^3.3 || ^4.0",
        "symfony/dependency-injection": "^3.3 || ^4.0",
        "symfony/event-dispatcher": "^3.3 || ^4.0",
        "symfony/http-foundation": "^3.3 || ^4.0",
        "symfony/http-kernel": "^3.3 || ^4.0",
        "symfony/security-core": "^3.3 || ^4.0",
        "symfony/security-http": "^3.3 || ^4.0"
    },
    "require-dev": {
        "contao/manager-plugin": "~2.0",
        "friendsofphp/php-cs-fixer": "^2.12",
        "php-http/guzzle6-adapter": "^1.1"
    },
    "conflict": {
        "contao/manager-plugin": "<2.0 || >=3.0"
    },
```

Gehen wir mal auf die einzelnen Angaben ein:
- `"php": "^7.1",` -> Bedeutet die geforderte PHP-Version ist >=7.1 < 8.0
  - Für Contao 4.13 müsste das angepasst werden auf: `"php": "^7.4 || ^8.0",`
- `"doctrine/dbal": "^2.7",` -> Bedeutet doctrine/dbal Version ist >=2.7 < 3.0
  - Contao 4.13: `"doctrine/dbal": "^3.1",`
- `"symfony/config": "^3.3 || ^4.0",`
  - Contao 4.13: `"symfony/config": "^5.4",`
-  `"symfony/dependency-injection": "^3.3 || ^4.0",`
  - Contao 4.13: `"symfony/dependency-injection": "^5.4",`
- `"symfony/event-dispatcher": "^3.3 || ^4.0",`
  - Contao 4.13: `"symfony/event-dispatcher": "^5.4",`
- `"symfony/http-foundation": "^3.3 || ^4.0",`
  - Contao 4.13: `"symfony/http-foundation": "^5.4",`
- `"symfony/http-kernel": "^3.3 || ^4.0",`
  - Contao 4.13: `"symfony/http-kernel": "^5.4",`
- `"symfony/security-core": "^3.3 || ^4.0",`
  - Contao 4.13: `"symfony/security-core": "^5.4",`
- `"symfony/security-http": "^3.3 || ^4.0",`
  - Contao 4.13: `"symfony/security-http": "^5.4",`

Der Fehler bei der Installation bzw. die Fehler treten also auf, weil das Bundle versucht andere Abhängigkeiten zu installieren, als jene, die Contao installieren möchte -> Es fordert die falsche Version der Abhängigkeiten an.

Wenn diese Änderung in der composer.json getätigt wurden, dann sollte sich das Bundle wieder installieren lassen.
Habe es eben getestet und es bei mir in einem Contao 4.13 fehlerfrei installiert bekommen.

##

Bezüglich Code / Anpassungen im Code kann ich noch nichts sagen, das habe ich mir nicht genauer angesehen bisher.
Mir ist nur bei den Namespaces aufgefallen, dass dort noch Anpassungen bezüglich der gängingen Konventionen passieren könnten/sollten:

Also aus: 
- `namespace thescrat\LoginLinkBundle\ContaoManager;` -> `namespace Thescrat\LoginLinkBundle\ContaoManager;`

**Comment by thescrat** [comment]
@agonyz 
Super, vielen Dank für die Info. Funktioniert auch alles wie gewohnt? Ich werde mich dem Thema die nächsten Tage annehmen, weil ich gerade auch keine Zeit habe. Aber wenn "nur" die Abhängigkeiten das Problem sind, dann sollte das ja recht einfach gelöst werden. Ich werde es zeitnah selbst probieren und ne neue Version veröffentlichen.

Danke für die Mühe.

**Comment by agonyz** [comment]
@thescrat Aufgrund von fehlender Zeit konnte ich noch nicht testen, ob die Funktionalität weiterhin vorhanden ist, wie gewohnt.
Das sollte am Besten jemand testen, der die Erweiterung zuvor bereits in Verwendung hatte.

Gerne doch. Ansonsten sehe ich es mir mal selber an, sobald ich mehr Zeit habe (ggf. Wochenende) und könnte einen PR erstellen. Aber das muss ich erstmal sehen :)

**Comment by agonyz** [comment]
@thescrat Ich habe dir mal einen Pull-Request für eine Contao 4.13 kompatible Version mit ein paar Anmerkungen erstellt: https://github.com/thescrat/contao-loginlink/pull/6

Bitte gerne nochmal testen und ggf. gewünschte Änderungen einspielen, bevor du das alles veröffentlichst.
Bei Fragen kannst Du gerne einfach auf mich zukommen.

**Comment by thescrat** [comment]
Release 1.0.5 ist verfügbar und funktioniert ab Contao 4.13.*

**Comment by akroii** [comment]
Vielen Dank @agonyz @thescrat
