### ISSUE TITLE
Parameter bei Bedarf anfügen

### ISSUE THREAD

**Issue by akroii** [thescrat/contao-loginlink#8]
Hallo,
wäre es möglich, nach einem Redirect noch ein Parameter bei Bedarf anzufügen? Ich bräuchte so eine Funktionalität, da ich Anforderungen an Tracking habe, wenn ein Deeplink ausgeführt wurde. Wenn man hier noch einen freies Eingabefeld einfügt und man eigene get-Parameter eingeben könnte, hätte man die Möglichkeit nach dem Deeplink ein Formular zu filtern.

[https://github.com/thescrat/contao-loginlink/blob/master/src/EventListener/GeneratePageListener.php#L140](https://github.com/thescrat/contao-loginlink/blob/master/src/EventListener/GeneratePageListener.php#L140)
```diff
-    Controller::redirect(Controller::addToUrl('',false,['key']));
+    Controller::redirect(Controller::addToUrl('deeplink=done',false,['key']));
```
Ich könnte einen Pull-Request machen. Natürlich erstmal mit einfacher Funktionalität.

**Comment by thescrat** [comment]
Hi, 
also ich habs gerade bei mir ausprobiert, du kannst so viele Parameter anhängen wie du möchtest. Dieser Redirect lässt ja nur den GET Parameter key= verschwinden, alles andere bleibt weiterhin erhalten.

Versuch doch einfach mal hinter den /?key=123example&deeplink=done anzuhängen. 
Nach dem Login müsste dort dann /?deeplink=done stehen bleiben. 

Freu mich über ne kurze Info.

**Comment by akroii** [comment]
Ich bräuchte die Funktionalität tatsächlich überall und vorallem automatisch, da ich die verschiedenen Einstiegsseite der Nutzer nicht kenne. Daher kann ich nicht den Nutzern einen geänderten Link geben, mit dem Sie den Deeplink ausführen können. Dafür ist die Seite schon zu lange im Umlauf. Praktisch muss die Erweiterung mir ein Signal (in Form eines Parameters in der URL) geben, dass ein Deeplink ausgeführt wurde.

PS: hab das Beispiel oben angepasst.

**Comment by thescrat** [comment]
Aber dein Wunsch hat doch überhaupt nichts mit der Erweiterung zu tun. Wo ich den Parameter key= entferne, möchtest du dann einen Parameter (von innen heraus) anhängen beim Aufruf der Seite? 
Ich verstehe dein Problem, aber warum genau soll diese Funktionalität in diese Erweiterung? Es hat doch mit dem Loginprozess überhaupt nichts zu tun!

Du brauchst dir doch nur selbst ne kleine Erweiterung schreiben, die genau das macht.

**Comment by akroii** [comment]
Ich bräuchte es tatsächlich von innen heraus, beim Aufruf der Seite. Der Hintergrund hat tatsächlich nur mit gewissen Tracking-Hintergründen zu tuen. Ich habe schon versucht irgendwie an den Referrer zukommen. So kann ich dann einfach prüfen ob der key= in der URL steht und kann dann einen Datalayer via Google Analytics ausführen. Leider ist der immer leer. Hängt irgendwie mit dem Redirect-Controller zusammen.

Der Aufwand für eine separate Erweiterung ist viel höher, als eine bestehende zu erweitern. Mit meinem Beispiel oben, ist das ursprüngliche Problem meinerseits schon gelöst :) Auch bin ich nicht so tief im Backend drin, dass mir das flüssig von der Hand gehen würde :/

**Comment by thescrat** [comment]
Dein Wunsch ist ein ganz spezieller Fall, der auch der Erweiterung keinen Mehrwert bringt und nichts mit dem Thema Login zu tun hat. Daher kann ich, trotz des erhöhten Aufwand nur auf eine separate Erweiterung verweisen. In dieser Erweiterung hat, wenn auch technisch möglich, diese Funktion nichts zu suchen.

Daher schließe ich das hier mal.
