### ISSUE TITLE
Bisher kein erfolgreicher Login möglich

### ISSUE THREAD

**Issue by ThomasKettner** [thescrat/contao-loginlink#9]
Hallo,

ich habe die Erweiterung mal in einer aktuellen Umgebung getestet.
Contao V 4.13.35

Leider war der Login mit dem ?key= Parameter noch nicht von Erfolg gekrönt.
Irgendeine Idee was hier ursächlich sein kann oder wie ich es debuggen kann?

Der Key ist beim Mitglied ordnungsgemäß hinterlegt.

**Comment by thescrat** [comment]
Hallo Thomas,
hast du im Root der Seitenstruktur auch den Login-Link per Checkbox aktiviert?
Ich habe die Erweiterung unter mehreren aktuellen 4.13.35 laufen und hab bisher keinen Fehler feststellen können.
Denke, dass hier nur der Haken vergessen wurde zu setzen um die Erweiterung für den Seitenbaum zu aktivieren.
Gib mir gerne kurzes Feedback.

**Comment by ThomasKettner** [comment]
Du hast recht!
Das hatte ich übersehen/überlesen.
Nun funktioniert es!
Besten Dank und frohe Festtage!

**Comment by thescrat** [comment]
Kein Problem. Viel Spaß mit der Erweiterung. Dir auch schöne Festtage
